FROM node:20-alpine
WORKDIR /app
COPY ./server/prisma ./server/prisma
COPY ./server/package.json ./server/package.json
COPY ./server/package-lock.json ./server/package-lock.json

WORKDIR /app/server
RUN npm install

COPY ./server/ ./

EXPOSE 8081
CMD ["npm", "run", "dev:docker"]